### ISSUE TITLE
Store the note in projects/ path

### ISSUE THREAD

**Issue by eknath-iyer** [aziz/PlainNotes#23]
In the Notes.sublime-settings file, if there were a way to reference the current projects' workspace and (maybe) create a sub directory there called 'Notes'. so something like `{"root": "${project_path}/Notes"}`, it would be very useful.

PS: I'm not certain if this can already be done. (I'm on windows using ST3)

**Comment by fk128** [comment]
feature has been added in version 0.1.5. To configure a directory for a given project you need to add the following to your `.sublime-project` file:

```json
"settings":
	{
 		"PlainNotes": 
 		{
 			"root": "/path/to/my/notes/dir"
 		}
	}
```

**Comment by eknath-iyer** [comment]
Perfect. Thanks
