### ISSUE TITLE
What markup is supported here?

### ISSUE THREAD

**Issue by pravic** [aziz/PlainNotes#26]
Hi.

Couldn't find what markup is supported by PlainNotes. Markdown? Or own custom syntax? I know about YAML (enabled in settings).

Can you explain the [Note.tmLanguage](https://github.com/aziz/PlainNotes/blob/master/Note.tmLanguage)?

**Comment by aziz** [comment]
It's Markdown + some extra features that I've not been able to document yet. If you look at the files in `Tests` directory in sublime you'll see some of those extra features. 
Documentation is something that PlainNotes lacks the most at the moment.

**Comment by pravic** [comment]
Thanks
