### ISSUE TITLE
Option + click for column selection is not working on OS X

### ISSUE THREAD

**Issue by ccampbell** [aziz/PlainNotes#32]
I noticed recently that option + click was no longer working on Sublime so I manually went through my packages and disabled them one at a time until it started working again.  Turns out that PlainNotes is the culprit.

I'd be happy to provide you additional information if you need help debugging.

I'm using Sublime Text 3 (build 3083)

Pretty sure the culprit is 6e0703d191c13be0db4232f7d5a964602d78d849

**Comment by aziz** [comment]
Yep, we should remove mouse mapping for now. the API provided by sublime is very limited and does not provide a way to bind a mouse interaction to a particular context.

**Comment by aziz** [comment]
I reverted all the mouse interactions in the new release. now you can just use `enter` to open links or preview images
