### ISSUE TITLE
Change default color for notes

### ISSUE THREAD

**Issue by mbiokyle29** [aziz/PlainNotes#33]
Hello,

I was wondering if there was a way to specify the default color for new notes. I tried `note_color_scheme` and `color_scheme` but neither seemed to work.

Thanks for making such a wonderful package!

**Comment by aziz** [comment]
It's a bit tricky and should be documented in README I guess. Anyway, here is how you should do this:

While looking at a note go to `Preferences > Settings - More > Syntax Specific - User`. This will open a file in you User directory called `Note.sublime-settings` it's a normal sublime settings file. add this rule: 

```json
{
  "color_scheme": "Packages/PlainNotes/Color Schemes/Sticky-Yellow.tmTheme"
}
```
Other colors available are:
- Sticky-Blue.tmTheme
- Sticky-BlueLight.tmTheme
- Sticky-Gray.tmTheme
- Sticky-Green.tmTheme
- Sticky-GreenLight.tmTheme
- Sticky-Orange.tmTheme
- Sticky-Pink.tmTheme
- Sticky-Purple.tmTheme
- Sticky-White.tmTheme
- Sticky-Yellow.tmTheme

**Comment by mbiokyle29** [comment]
Works perfect. Thanks!
