### ISSUE TITLE
Setting "note_color_scheme": "Packages/PlainNotes/Color Schemes/Sticky-White.tmTheme"

### ISSUE THREAD

**Issue by brennemankyle** [aziz/PlainNotes#48]
"note_color_scheme": "Packages/PlainNotes/Color Schemes/Sticky-White.tmTheme"
does nothing in Plain Notes -> Settings - User. New notes have the yellow theme

also note_color_scheme should be in Plain Notes -> Settings - Default.

I'm using sublime text 3

**Comment by fakhrullah** [comment]
Quoting https://github.com/aziz/PlainNotes/issues/33

> **While looking at a note** go to Preferences > Settings - More > Syntax Specific - User. This will open a file in you User directory called Note.sublime-settings it's a normal sublime settings file. add this rule:
> 
> ```
> {
>   "color_scheme": "Packages/PlainNotes/Color Schemes/Sticky-Yellow.tmTheme"
> }
> ```
> 
>

**Comment by brennemankyle** [comment]
thx!

**Comment by fakhrullah** [comment]
You are welcome. :smile: 
I am new at github issue discussion, but I think, you should close this, if your problem is solved.
