### ISSUE TITLE
PermissionError WinError 5 (Local Google Drive Folder)

### ISSUE THREAD

**Issue by naxmefy** [aziz/PlainNotes#49]
Info:
- Sublime Text 3
- windows 10 pro 64
- inside google drive (for cloud sync) (same issue in onedrive folder)

what done:
- setup a project in the google drive folder 
- setup sublime-project file like:

``` JavaScript
{
    "folders":
    [
        {
            "path": "notes",
            "file_exclude_patterns": ["desktop.ini"]
        },
        {
            "path": "todos",
            "file_exclude_patterns": ["desktop.ini"]
        },
        {
            "path": ".",
            "folder_exclude_patterns": ["notes", "todos"],
            "file_exclude_patterns": ["desktop.ini"]
        }
    ],

    "settings": {
        "PlainNotes": {
            "root": "notes"
        }
    }
}
```

Tried to create new note but got following error:

```
Traceback (most recent call last):
  File "notes in C:\Users\naxmefy\AppData\Roaming\Sublime Text 3\Installed Packages\PlainNotes.sublime-package", line 142, in create_note
  File "./python3.3/os.py", line 262, in makedirs
PermissionError: [WinError 5] Permission denied: 'notes'
```

**Comment by fk128** [comment]
try an absolute path for "root" instead of just "notes".

**Comment by guillaume8375** [comment]
I have the same problem on Ubuntu 16.10 64b with Sublime Text build 3126.

When I try to create a note in my Dropbox folder (/home/Dropbox/Notes), I get the following message in the Sublime Text console:

    Traceback (most recent call last):
      File "notes in /home/guillaume/.config/sublime-text-3/Installed Packages/PlainNotes.sublime-package", line 151, in create_note
    PermissionError: [Errno 13] Permission denied: '/home/guillaume/Dropbox/Notes/Essai 3.note'`

When I change the PlainNotes settings to create notes directly in my Home folder /home/Notes, there is no problem and the notes I make are saved in this folder.
